import type { Question } from "./types";

export const questionBank: Question[] = [
  // ── Geografi ─────────────────────────────────────────────────────────────
  {
    id: 1,
    question: "Apa ibu kota negara Jepang?",
    options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 2,
    question: "Sungai terpanjang di dunia adalah…",
    options: ["Amazon", "Nil", "Yangtze", "Mississippi"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 3,
    question: "Gunung tertinggi di dunia adalah…",
    options: ["K2", "Kangchenjunga", "Everest", "Lhotse"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 4,
    question: "Negara manakah yang memiliki garis pantai terpanjang di dunia?",
    options: ["Indonesia", "Australia", "Kanada", "Rusia"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 5,
    question: 'Benua manakah yang dikenal sebagai "Benua Hitam"?',
    options: ["Asia", "Amerika", "Afrika", "Australia"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  // ── Sains ────────────────────────────────────────────────────────────────
  {
    id: 6,
    question: 'Unsur kimia dengan simbol "Au" adalah…',
    options: ["Perak", "Emas", "Aluminium", "Tembaga"],
    correctIndex: 1,
    category: "🔬 Sains",
  },
  {
    id: 7,
    question: "Berapa kecepatan cahaya dalam vakum (km/s)?",
    options: ["150.000", "300.000", "450.000", "600.000"],
    correctIndex: 1,
    category: "🔬 Sains",
  },
  {
    id: 8,
    question: "Planet terbesar di tata surya kita adalah…",
    options: ["Saturnus", "Neptunus", "Jupiter", "Uranus"],
    correctIndex: 2,
    category: "🔬 Sains",
  },
  {
    id: 9,
    question: "DNA merupakan singkatan dari…",
    options: [
      "Deoxyribonucleic Acid",
      "Dinitrogen Acid",
      "Dynamic Nuclear Atom",
      "Dense Nucleotide Array",
    ],
    correctIndex: 0,
    category: "🔬 Sains",
  },
  {
    id: 10,
    question: "Siapakah ilmuwan yang merumuskan Hukum Gravitasi Universal?",
    options: [
      "Albert Einstein",
      "Galileo Galilei",
      "Isaac Newton",
      "Nikola Tesla",
    ],
    correctIndex: 2,
    category: "🔬 Sains",
  },
  // ── Sejarah ─────────────────────────────────────────────────────────────
  {
    id: 11,
    question: "Pada tahun berapa Indonesia merdeka?",
    options: ["1942", "1944", "1945", "1946"],
    correctIndex: 2,
    category: "📜 Sejarah",
  },
  {
    id: 12,
    question: "Siapakah proklamator kemerdekaan Indonesia?",
    options: [
      "Soeharto & Hamengkubuwono",
      "Soekarno & Hatta",
      "Syahrir & Yamin",
      "Sudirman & Nasution",
    ],
    correctIndex: 1,
    category: "📜 Sejarah",
  },
  {
    id: 13,
    question: "Perang Dunia II berakhir pada tahun…",
    options: ["1943", "1944", "1945", "1946"],
    correctIndex: 2,
    category: "📜 Sejarah",
  },
  {
    id: 14,
    question: "Tembok Berlin diruntuhkan pada tahun…",
    options: ["1985", "1987", "1989", "1991"],
    correctIndex: 2,
    category: "📜 Sejarah",
  },
  {
    id: 15,
    question: "Dinasti manakah yang membangun Tembok Besar China?",
    options: ["Tang", "Song", "Qin", "Han"],
    correctIndex: 2,
    category: "📜 Sejarah",
  },
  // ── Budaya & Seni ────────────────────────────────────────────────────────
  {
    id: 16,
    question: 'Siapakah pelukis terkenal yang menciptakan karya "Mona Lisa"?',
    options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Caravaggio"],
    correctIndex: 2,
    category: "🎨 Budaya & Seni",
  },
  {
    id: 17,
    question:
      "Alat musik tradisional Indonesia yang dimainkan dengan cara dipukul adalah…",
    options: ["Angklung", "Gamelan", "Kolintang", "Saluang"],
    correctIndex: 1,
    category: "🎨 Budaya & Seni",
  },
  {
    id: 18,
    question: 'Siapakah penulis novel "Harry Potter"?',
    options: [
      "Stephenie Meyer",
      "J.R.R. Tolkien",
      "J.K. Rowling",
      "C.S. Lewis",
    ],
    correctIndex: 2,
    category: "🎨 Budaya & Seni",
  },
  // ── Teknologi ────────────────────────────────────────────────────────────
  {
    id: 19,
    question: "Siapakah pendiri perusahaan Microsoft?",
    options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Elon Musk"],
    correctIndex: 1,
    category: "💻 Teknologi",
  },
  {
    id: 20,
    question: 'Kepanjangan dari "HTTP" dalam konteks web adalah…',
    options: [
      "HyperText Transfer Protocol",
      "High Technology Transfer Process",
      "Hyperlink Text Transmission Protocol",
      "HyperText Transmission Program",
    ],
    correctIndex: 0,
    category: "💻 Teknologi",
  },
  {
    id: 21,
    question: "Satuan penyimpanan data terbesar dari daftar berikut adalah…",
    options: ["Gigabyte", "Terabyte", "Kilobyte", "Megabyte"],
    correctIndex: 1,
    category: "💻 Teknologi",
  },
  {
    id: 22,
    question:
      "Bahasa pemrograman yang dikembangkan oleh Brendan Eich pada 1995 adalah…",
    options: ["Python", "Java", "JavaScript", "PHP"],
    correctIndex: 2,
    category: "💻 Teknologi",
  },
  // ── Olahraga ─────────────────────────────────────────────────────────────
  {
    id: 23,
    question:
      'Cabang olahraga manakah yang menggunakan istilah "love" untuk angka nol?',
    options: ["Bulu Tangkis", "Tenis", "Squash", "Ping Pong"],
    correctIndex: 1,
    category: "⚽ Olahraga",
  },
  {
    id: 24,
    question: "Olimpiade modern pertama kali diadakan di negara mana?",
    options: ["Inggris", "Prancis", "Yunani", "Amerika Serikat"],
    correctIndex: 2,
    category: "⚽ Olahraga",
  },
  {
    id: 25,
    question:
      "Jumlah pemain dalam satu tim sepak bola (termasuk penjaga gawang) adalah…",
    options: ["9", "10", "11", "12"],
    correctIndex: 2,
    category: "⚽ Olahraga",
  },
  {
    id: 26,
    question: "Bika Ambon adalah makanan khas dari daerah mana?",
    options: ["Samarinda", "Medan", "Ambon", "Gorontalo"],
    correctIndex: 1,
    category: "🍨 Kuliner",
  },
  {
    id: 27,
    question:
      "Berikut ini yang bukan termasuk Wakil Presiden Soeharto adalah...",
    options: [
      "Sri Sultan Hamengkubowono IX",
      "Try Sutrisno",
      "Prof. Dr.- Ing Bacharuddin Jusuf Habibie",
      "Hamzah Haz",
    ],
    correctIndex: 3,
    category: "📜 Sejarah",
  },
  {
    id: 28,
    question: "Asian Games pertama kali diadakan di negara mana?",
    options: ["Thailand", "Indonesia", "Malaysia", "India"],
    correctIndex: 3,
    category: "⚽ Olahraga",
  },
  {
    id: 29,
    question: "SEA Games pertama kali diadakan di negara mana?",
    options: ["Thailand", "Indonesia", "Malaysia", "India"],
    correctIndex: 0,
    category: "⚽ Olahraga",
  },
  {
    id: 30,
    question:
      "Berikut ini yang bukan termasuk julukan negara Indonesia adalah...",
    options: [
      "Lumbung Padi Asia",
      "Negeri Seribu Candi",
      "Paru-Paru Dunia",
      "Macan Asia Yang Tertidur",
    ],
    correctIndex: 0,
    category: "🌏 Geografi",
  },
  {
    id: 31,
    question: "Alat untuk mengukur suhu adalah…",
    options: ["Barometer", "Higrometer", "Termometer", "Seismometer"],
    correctIndex: 2,
    category: "🔬 Sains",
  },
  {
    id: 32,
    question: "Hewan tercepat didunia adalah…",
    options: ["Elang Peregrine", "Sailfish", "Cheetah", "Ikan Marlin"],
    correctIndex: 0,
    category: "🐈 Animalia",
  },
  {
    id: 33,
    question: "Gunung tertinggi di Pulau Jawa adalah…",
    options: [
      "Gunung Ceremai",
      "Gunung Slamet",
      "Gunung Arjuno",
      "Gunung Semeru",
    ],
    correctIndex: 3,
    category: "🌏 Geografi",
  },
  {
    id: 34,
    question: "ASEAN didirikan pada tahun…",
    options: ["1960", "1967", "1971", "1980"],
    correctIndex: 1,
    category: "📜 Sejarah",
  },
  {
    id: 35,
    question: "Siapa penemuan lampu pijar?",
    options: [
      "Thomas Alfa Edison",
      "Nikola Tesla",
      "Alexander Graham Bell",
      "Michael Faraday",
    ],
    correctIndex: 0,
    category: "💻 Teknologi",
  },
  {
    id: 36,
    question: "Planet yang dikenal sebagai Planet merah adalah…",
    options: ["Venus", "Neptunus", "Merkurius", "Mars"],
    correctIndex: 3,
    category: "🔬 Sains",
  },
  {
    id: 37,
    question: "Bahan utama dalam pembuatan kaca adalah…",
    options: ["Pasir", "Tanah Liat", "Batu Kapur", "Logam"],
    correctIndex: 0,
    category: "🔬 Sains",
  },
  {
    id: 38,
    question: "Samudra terbesar di dunia adalah…",
    options: [
      "Samudra Atlantik",
      "Samudra Pasifik",
      "Samudra Hindia",
      "Samudra Arktik",
    ],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 39,
    question: "Negara dengan luas wilayah terbesar di dunia adalah…",
    options: ["China", "Russia", "India", "Amerika Serikat"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 40,
    question: "Ibu kota negara Australia adalah…",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 41,
    question: "Danau terbesar di dunia adalah…",
    options: [
      "Danau Baikal",
      "Danau Superior",
      "Danau Victoria",
      "Danau Tanganyika",
    ],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 42,
    question: "Planet terbesar kedua di tata surya kita adalah…",
    options: ["Saturnus", "Bumi", "Jupiter", "Mars"],
    correctIndex: 0,
    category: "🔭 Sains",
  },
  {
    id: 43,
    question: "Penemu teori relativitas adalah…",
    options: [
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Nikola Tesla",
    ],
    correctIndex: 0,
    category: "🔭 Sains",
  },
  {
    id: 44,
    question: "Peristiwa Sumpah Pemuda terjadi pada tahun…",
    options: ["1908", "1928", "1945", "1965"],
    correctIndex: 1,
    category: "📜 Sejarah",
  },
  {
    id: 45,
    question: "Ibukota negara Rusia adalah…",
    options: ["Moskow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
    correctIndex: 0,
    category: "🌏 Geografi",
  },
  {
    id: 46,
    question: "Zat hijau daun yang berperan dalam fotosintesis adalah…",
    options: ["Hemoglobin", "Klorofil", "Melanin", "Karoten"],
    correctIndex: 1,
    category: "🔭 Sains",
  },
  {
    id: 47,
    question: "Waktu setelah Abad Kegelapan disebut…",
    options: ["Abad Pencerahan", "Abad Modern", "Abad Abad", "Abad Kegelapan"],
    correctIndex: 0,
    category: "📜 Sejarah",
  },
  {
    id: 48,
    question: "Palung terdalam di dunia adalah…",
    options: ["Tonga", "Kemadec", "Mariana", "Kuril"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 49,
    question: "Unsur kimia dengan simbol 'O' adalah…",
    options: ["Ozon", "Oksida", "Oksigen", "Oksigenasi"],
    correctIndex: 2,
    category: "🔭 Sains",
  },
  {
    id: 50,
    question: "Negara yang dikenal sebagai Negeri Sakura adalah…",
    options: ["China", "Korea Selatan", "Jepang", "Thailand"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 51,
    question: "Benua yang memiliki populasi terbanyak di dunia adalah…",
    options: ["Afrika", "Asia", "Eropa", "Amerika"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 52,
    question: "Ibukota negara Jerman adalah…",
    options: ["Munich", "Hamburg", "Berlin", "Frankfurt"],
    correctIndex: 2,
    category: "🌏 Geografi",
  },
  {
    id: 53,
    question: "Hewan yang dikenal sebagai raja hutan adalah…",
    options: ["Harimau", "Singa", "Gajah", "Serigala"],
    correctIndex: 1,
    category: "🐈 Animalia",
  },
  {
    id: 54,
    question: "Satuan SI untuk gaya adalah…",
    options: ["Joule", "Newton", "Watt", "Pascal"],
    correctIndex: 1,
    category: "🔭 Sains",
  },
  {
    id: 55,
    question:
      "Negara dengan jumlah penduduk terbanyak di dunia saat ini adalah…",
    options: ["China", "India", "Amerika Serikat", "Indonesia"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 56,
    question: "Siapa penemu telepon?",
    options: [
      "Thomas Edison",
      "Alexander Graham Bell",
      "Nikola Tesla",
      "Guglielmo Marconi",
    ],
    correctIndex: 1,
    category: "📜 Sejarah",
  },
  {
    id: 57,
    question: "Lapisan atmosfer tempat terjadinya cuaca adalah…",
    options: ["Stratosfer", "Mesosfer", "Troposfer", "Termosfer"],
    correctIndex: 2,
    category: "🔭 Sains",
  },
  {
    id: 58,
    question: "Ibukota negara Italia adalah…",
    options: ["Milan", "Roma", "Napoli", "Venice"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 59,
    question:
      "Organ tubuh manusia yang berfungsi untuk menyaring darah adalah…",
    options: ["Jantung", "Ginjal", "Hati", "Paru-paru"],
    correctIndex: 1,
    category: "🔭 Sains",
  },
  {
    id: 60,
    question: "Negara asal Olimpiade modern pertama adalah…",
    options: ["Prancis", "Yunani", "Italia", "Jerman"],
    correctIndex: 1,
    category: "⚽ Olahraga",
  },
  {
    id: 61,
    question: "Ibukota negara Arab Saudi adalah…",
    options: ["Jeddah", "Riyadh", "Mecca", "Medina"],
    correctIndex: 1,
    category: "🌏 Geografi",
  },
  {
    id: 62,
    question: "Unsur kimia dengan simbol 'Fe' adalah…",
    options: ["Fluorin", "Fosfor", "Besi", "Emas"],
    correctIndex: 2,
    category: "🔭 Sains",
  },
  {
    id: 63,
    question: "Planet terdekat dengan matahari adalah…",
    options: ["Venus", "Merkurius", "Bumi", "Mars"],
    correctIndex: 1,
    category: "🔭 Sains",
  },
  {
    id: 64,
    question: "Ibukota negara Spanyol adalah…",
    options: ["Barcelona", "Sevilla", "Valencia", "Madrid"],
    correctIndex: 3,
    category: "🌏 Geografi",
  },
  {
    id: 65,
    question: "Hewan yang hidup di dua alam disebut…",
    options: ["Mamalia", "Reptil", "Amfibi", "Aves"],
    correctIndex: 2,
    category: "🐈 Animalia",
  },
  {
    id: 66,
    question: "Perang Dunia I dimulai pada tahun…",
    options: ["1912", "1914", "1916", "1918"],
    correctIndex: 1,
    category: "📜 Sejarah",
  },
  {
    id: 67,
    question: "Alat untuk mengukur gempa bumi adalah…",
    options: ["Barometer", "Seismograf", "Termometer", "Higrometer"],
    correctIndex: 1,
    category: "🔭 Sains",
  },
  {
    id: 68,
    question: "Ibukota negara Korea Selatan adalah…",
    options: ["Busan", "Daegu", "Incheon", "Seoul"],
    correctIndex: 3,
    category: "🌏 Geografi",
  },
  {
    id: 69,
    question: "Presiden Indonesia ke-3 adalah…",
    options: ["B.J. Habibie", "Abdurrahman Wahid", "Megawati", "Soeharto"],
    correctIndex: 0,
    category: "📜 Sejarah",
  },
  {
    id: 70,
    question: "Zat cair yang dibutuhkan manusia untuk bertahan hidup adalah…",
    options: ["Minyak", "Alkohol", "Air", "Asam"],
    correctIndex: 2,
    category: "🔭 Sains",
  },
];

/** Returns `count` questions chosen randomly from the bank (no duplicates). */
export function pickRandomQuestions(count: number): Question[] {
  const shuffled = [...questionBank].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
